version: '3'

volumes:
  pg_data:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: server_coords
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwe45asd46
  db_init:
    image: postgres:13.10
    env_file: .env
    command: [ "bash", "-c", "sleep 5 && PGPASSWORD=qwe45asd46 psql -h db -U postgres -w -c 'CREATE DATABASE server_coords;'" ]
    depends_on:
      - db
  backend:
    build: ./server/
    env_file: .env
    depends_on:
      - db
  frontend:
    env_file: .env
    build: ./client/