# !запускается на 8001!

version: '3'

volumes:
  pg_data:

services:
  server:
    build:
      context: ./server
    ports:
      - "8000:8000"
    networks:
      - test_network
  db:
    image: postgres:13.10
    env_file: .env
    container_name: db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: server_coords
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwe45asd46
    networks:
      - test_network
  db_init:
    image: postgres:13.10
    env_file: .env
    command: [ "bash", "-c", "sleep 10 && PGPASSWORD=qwe45asd46 psql -h db -U postgres -w -c 'CREATE DATABASE server_coords;'" ]
    depends_on:
      - db
  backend:
    build: ./server/
    env_file: .env
    environment:
      - DB_HOST=db
    depends_on:
      - db
    ports:
      - "8001:8000"
    networks:
      - test_network


networks:
  test_network:
    driver: bridge